name: Promo Bot

on:
  schedule:
    # Каждый Пятница в 12:00 по Москве
    - cron: "0 9 * * FRI"  # Москва = UTC+3 → 09:00 UTC = 12:00 MSK

  workflow_dispatch:  # ручной запуск

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run Promocode Check CI
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MODE: CI
        run: |
          python3 main.py
